SchoolChoicePlayground/Controllers/SchoolAppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolChoicePlayground.Models;
using Microsoft.AspNet.Identity;

namespace SchoolChoicePlayground.Controllers
{
    public class SchoolAppController : Controller
    {
        public AppRepository Repo { get; set; }

        public SchoolAppController() : base() // Inherits all props and methods from base SchoolAppController
        {
            Repo = new AppRepository();
        }

        // GET: SchoolApp
        [Authorize]
        public ActionResult Index(Schoolappuser currentUser)
        {
            //if (currentUser != null)
            //{
                //Repo.AddUserToContext(currentUser);
            //}

            List<School> all_schools = Repo.GetAllSchools();
            return View(all_schools);
        }

        // GET: SchoolApp/Details/5
        public ActionResult UserProfile()
        {
            //string user_id = User.Identity.GetUserId();
            //SchoolAppUser currentUser = Repo.GetAllUsers().Where(u => u.RealUser.Id == user_id).Single();
            return View();
        }

        // GET: SchoolApp/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SchoolApp/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SchoolApp/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SchoolApp/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SchoolApp/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SchoolApp/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SchoolChoicePlayground/Controllers/SchoolApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolChoicePlayground.Models;
using Microsoft.AspNet.Identity;

namespace SchoolChoicePlayground.Controllers
{
    public class SchoolApplicationController : Controller
    {
        public AppRepository Repo { get; set; }

        public SchoolApplicationController() : base() // Inherits all props and methods from base SchoolAppController
        {
            Repo = new AppRepository();
        }

        // GET: SchoolApp
        [Authorize]
        public ActionResult Index()
        {

            MyUser new_user = new Models.MyUser
            {
                email = User.Identity.GetUserName(),
                alerts = false,
                AspUser = User.Identity.GetUserId()
            };
            // This method checks whether the user is already in DB.
            Repo.AddUserToContext(new_user);
            List<School> all_schools = Repo.GetAllSchools();
            return View(all_schools);
        }

        public ActionResult UserProfile()
        {
            string user_id = User.Identity.GetUserId();
            MyUser current_user = Repo.GetUserById(user_id);
            return View(current_user);
        }

        // GET: SchoolApp/Create
        public ActionResult SchoolProfile()
        {

            return View();
        }

        // POST: SchoolApp/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SchoolApp/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SchoolApp/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SchoolApp/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SchoolApp/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public string GetUserId()
        {
            string user_id = User.Identity.GetUserId();
            return user_id;
        }
    }
}

SchoolChoicePlayground/Views/Shared/_AppNav.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div>@Html.ActionLink("UnCHARTERed Territory", "Index", "SchoolApplication", new { area = "" }, new { @class = "navbar-brand" })</div>
        </div>
        <div class="navbar-collapse collapse"> 
            <ul class="nav navbar-nav navbar-right">
                @*<li><a href="/#/schoolProfile">Profile</a></li>*@
                @*This was the original link to call views server-side*@
                <li>@Html.ActionLink("Profile", "UserProfile", "SchoolApplication", new { area = "" }, null)</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

SchoolChoicePlayground/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>UnChartered Territory</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/myStyles")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body ng-app="schoolChoice">
    @Html.Partial("_AppNav")
    <div class="container body-content">
        @*<div ng-view></div>*@
        @RenderBody()
        @RenderSection("SPAViews", required: false)
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - UnChartered Territory</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angularjs")
    @RenderSection("Scripts", required: false)
</body>
</html>

SchoolChoicePlayground/Views/Shared/_Nav.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.Partial("_LoginPartial")
        </div>
        @Html.ActionLink("UnCHARTERed Territory", "Index", "SchoolApp", new { area = "" }, new { @class = "navbar-brand" })
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Profile", "UserProfile", "SchoolApp", new { area = "" }, null)</li>
                @*<li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>*@
            </ul>
           
        </div>
    </div>
</div>